{
 "title": "Gitops",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(gitops_check_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Deployments",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (gitops_deployments_active_total{status=\"running\",instance=~\"$instance\"})",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "sum by (status) (gitops_deployments_active_total{status!=\"running\",instance=~\"$instance\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Last Deployment Change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (status) ((time() - gitops_deployments_change_timestamp_seconds{instance=~\"$instance\"}) * (gitops_deployments_change_timestamp_seconds{instance=~\"$instance\"} != bool 0))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Deployment Operations (24h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (operation) (increase(gitops_deployments_operations_total{instance=~\"$instance\"}[24h]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "GitOps Checks (24h)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(gitops_check_total{instance=~\"$instance\"}[24h]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Time Since Last Check (by status)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (status) ((time() - gitops_check_timestamp_seconds{instance=~\"$instance\"}) * (gitops_check_timestamp_seconds{instance=~\"$instance\"} != bool 0))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"gitops-compose\",instance=~\"$instance\"}\n| label_format timestamp=\"{{__timestamp__}}\"\n| line_format `{{.instance}}/{{.container}}: {{__line__}}`"
    }
   ]
  }
 ]
}