services:
  gitops:
    build: .
    ports:
      - 2112:2112
    environment:
      CHECK_INTERVAL_IN_SECONDS: 5
      REPOSITORY_PATH: /repository
      REPOSITORY_USERNAME: ${REPOSITORY_USERNAME}
      REPOSITORY_PASSWORD: ${REPOSITORY_PASSWORD}
      DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
      DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME}
      DOCKER_REGISTRY_PASSWORD: ${DOCKER_REGISTRY_PASSWORD}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test-repos/deployments:/repository
