services:
  gitops:
    build: .
    ports:
      - 127.0.0.1:2112:2112
    environment:
      DOCKER_REGISTRIES: ${DOCKER_REGISTRIES}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test-repos/temp-deployment:/repository
